[[file:index.org][Return to Home]]
* MAJOR
** BASE
*** Kerry Eurodyne
    - Class: Rockerboy
    - Wiki Link: https://cyberpunk.fandom.com/wiki/Kerry_Eurodyne
:BIO:
Kerry became famous by being vocals and lead/rhythm guitar for Samurai.
He shared his friend's, Johnny Silverhand, view of changing the world through music,
but at some point wanted to bring his own message to the people. Ever since he and
superstar Johnny Silverhand parted ways, after the disbanding of Samurai,
he became a solo artist. Later he was also extremely successful as a solo artist and
dealt with a lot of injustice and terrible events in world affairs in his texts,
which his audience - much to their concern - did not always understand correctly.
He's withstood the test of time. His albums have gone platinum.
His broken guitars have been auctioned for thousands of Eurodollars.
And his singing voice is recognized worldwide.
:END:
*** Morgan Blackhand
    - Class: Solo
    - Link: https://cyberpunk.fandom.com/wiki/Morgan_Blackhand
:BIO:
Morgan Blackhand is a pragmatic Solo with an anodized black-chrome cyberlimb arm.
Generally considered to be a "Solo's Solo", with years of experience and ops under his belt.
Rated as the number one Solo professional in the business by the Solo of Fortune Annual 2020 Awards in the US.

Morgan Blackhand is defined by the fact that he is a pragmatist.
Blackhand survives because he is street-smart and is constantly looking out for his own best interest.
His reputation as a top Solo is partly due to the fact that he is able to capture targets alive,
rather than simply killing them. He is also a skilled Techie, as not to have to rely on others to
repair his tech, and has some training in martial arts.

Morgan's handling of incidents, like the attempted kidnapping of Kerry Eurodyne, show the touch of the mastery.
It is interesting to note that all five of the kidnappers were captured by Morgan (alone),
and turned over to Federal Authorities. They were bruised, battered and beaten, but alive.
Only a master like Blackhand can eliminate a threat and embarrass the group's sponsors.

Morgan goes for the highest bidder, he has no agenda and no aspirations to be anything more than he is.
Instead he only takes the jobs given to him and accomplishes them however he sees fit. 
:END:
*** Sgt. Max Hammerman
    - Class: Cop
:BIO:
Max Hammerman is a sergeant for the Night City Police Department in the Cyberpunk 2020 setting.
Noted to have specifically worked with one of the departments Cybersquads.

"Drop it, punk. I don't wanna hear your life story, and I don't care what Society did to you. 
I just wanna see that gun hit the floor. Now... Before I give you an extra nostril.."
:END:
*** Phil "Nacho" Hernandez
    - Class: Fixer
:BIO:
Phil Hernandez is a fixer mentioned in the Cyberpunk 2020 Core Rulebook.[1]
Quotes

"Don't give me this 'Robin Hood' Stuff. I'm doin' a job, no more. 
I give people what they want, an' they pay me out.

Okay, so maybe I even a few scores here and there, but that's good for Business. 
You make a friend- they'll take you in when the Street's too hot, 
and they'll pass you a few bits of data when you call in the markers. But that's business.

I got a slogan... 'How much you pay me?'" 
:END:
*** Nomad Santiago
    - Class: Nomad
:BIO:
Santiago is a Nomad who runs with the Aldecaldo Pack;
displaced farmers thrown off their land by the Corporations.

Santiago is a simple guy-- he likes girls, guns and fast cyberbikes.
He teams with Rogue mostly because she's the one girl he hasn't been able to score with yet.

-- Quotes --

"Guns. Guns and cyberbikes. That's how we hold the line. We don't have any 
home except the Caravan. We don't have any rights except what we take. 
We get run out of town by the cops; we get raided by the roadwarrior packs, 
and we survive because we've got guns and bikes...

There's kids, old men and women- families here. 
This ain't no boostergang. 
These people are my family." 
:END:

*** Spider Murphy
    - Class: Netrunner
    - Link:
:BIO:
"You guys who live in Realspace; you move so slow. Me I like Netspace. It moves fast. You don't get old, 
you don't get slow and sloppy. You just leave the meat behind and go screamin'.

First system I ever hit, I think they had some weeflerunner playin' Sysop for them. 
I burned in, and jolted the guy with a borrowed Hellbolt, and did the major plunder 
action all over the Data Fortress.

Somewhere out there is a guy with half his forebrain burned out. 
I wonder if they ever found the body. I wonder if they'll find mine the same way..."

-Spider Murphy, Cyberpunk 2020 Core Rulebook

Alternate Timeline:

In Firestorm: Shockwave Spider Murphy recovered Alt, marked her personality file and threw her
somewhere on the net to be retrieved later. She also captured Kei Arasaka in his escape submarine
and pressured him into committing "seppuku" by running the Soulkiller 3.0 on himself; he then did so. 
:END:
*** Lyle McClellan
    - Class: Medias
:BIO:
Lyle McClellan is a media for network 54.

"Okay, so it's dangerous. Look, I'll tell you something. 
When I was a kid, I use to watch those reporters on the TV news. 
They wore those chill trenchcoats and were always broadcasting from some exotic place like 
Mozambique or Saigon. They went right into the Central American warzones with the cybergrunts, 
and they got the story even when the shooting was maximally fierce.

That's the part I like; the danger." 
:END:
 
*** Mister Ice
    - Class: Techie
:BIO:
"So you want me to build a delay switch into the thing? And you don't care about the explosion radius?

No problem. At least you got a simple job. Last guy in here, 
he wanted me to build him a cyber hand that had a built-in ...aw, frack, you don't wanna know. 
People want the weirdest stuff these days...

I hear with the new cyberwear they're coming up with in Chiba, 
you're gonna be able to cram your body with more options than a frackin' 
Mercedes aerodyne...No problem. If you can get parts, I can fix it. Count on it, chombatta." 
:END:

** CUSTOM
*** Doctor John
:CONFIDENTIAL:
bdfa785fe146c1815c8e38fe26ad42e6a64544
bdfa5a54e50f92884cc9
baf03119a066e6fa289057
ecfa527dd415ce9b2e861bba2ee875cb8c686e7b4352cd182c8cf62b6f2d10c77656b3b6cd43032c8ad60dcd1ddb150e70c6b0791c8b08e996039fae0a34fa932e23447ae5490e895a90694f7a351752c7b1a3c34251fd26fb571bd4ab
ecfa3b02b015ce9b5ce36aba2ee801aefe106e7b4331a266508cf62b0e5964a07656b3dab8207c2c8ad660be1ddb156c1fa2db791c8b6d95f6039fae6959d9932e233c5284390e895ae4106249351752b4d0d5b44251fd448f2a1bd4ab
baf03119a066c6c210a657
bdfa585fef41dade0ff97dd027a551fdba493a0d
bdfa5352e947889b2fab3cec37a62b
bdfa5a55e650d1cf1db734f53cf201d8a04f2a680c31c03819dfaa495c182af17602d793fe66216f839a34ac49c8153f5ae7c053
bdfa5e47e85bdbd815b724a0728947fca6432f6969
bdfa5752ee52889b39ad3af63bbb49a2ef622f69176488
baf03119a073d3d615af24ba10a942e5a85221720d7588
bdfa5c52ee5292fd1dae34f62bc2
bdfa595cf45d92cb1db138f426bb01efbd456e660f78f4326a
bdfa5d52ed5cdec25caa2eba3ba601eaae4e29621131e4250fc1aa7f461c64e33945f795f7202a638f854a
bdfa4843e55bc69b1fab34f636a04ee1ab0027694352ed25108cd97e4c0c36f73f4b99
bdfa5352f315d39b1eb132ee3aad53aeae4e2a271078f12305de80
baf03119a078ddcf15b53cee3ba74ffdc5
bdfa4f41e15cc6c846e314f426ad4de2aa433a72027da27140e8ef7f4f1a2cf03220
bdfa4d52ec40d7df5c9338e821a74fb4ef662f6a0a7dfb5d
bdfa4d52ec40d79b31ac2eee68e877eba1472b660d72e75d
bdfa5d56e55992fa1eac28ee729844e1bf4c2b3d4358a23b09c7ef2b4f1529fa255eb39fee653a7599982586
bdfa4d52ec40d7df5c9332e921ad52fda64f203d4350a22505cfe5794a102af25c
baf03119a079dbdd19e318ec37a655fdc5
bdfa2a05a915f4d409ad39ba33e855ebae432662113eef320ed8e57924
bdfa2a0ba915ffde08e33be83bad4feaef5426750c64e53f40cfe56643162ab53f44e79fea653b78fc
bdfa2901a915f4da10b038ba13ab42fbbc413a6e0c7fa2380e8cff654b0d2cfc354bffdae872296f829f23e937
bdfa2907a915fada0cb324ba1ea757ebef6128610278f05d
bdfa2905a915f4d415af38fe72a901fea34120270c77a2321881e664581c36b52245b38feb656864978424fb5cd5506c76a28a2b05ca39c1a229
b0fa3b13a015c6d45ca131fb31a34cefa64c6e77067ef23b058280
bdfa2803a915f4d212a77dff2ab844fca64d2b691770ee7721e5aa64405920f0374eb398f764312c999060ed1dc45a3e4f88
b0fa3b13a015c6d31db77df233bb01e9a6562b694368ed2240cde9684b0a37b52245b38eea612c69d68525ef4fc24146
b0fa3b13a015d1c21ea62ff437bc48edef4920610c63ef3614c5e5650073
:END:

* MINOR
** BASE
** CUSTOM
