[[file:index.org][Return to Home]]
* MAJOR
** BASE
*** Kerry Eurodyne
    - Class: Rockerboy
    - Wiki Link: https://cyberpunk.fandom.com/wiki/Kerry_Eurodyne
:BIO:
Kerry became famous by being vocals and lead/rhythm guitar for Samurai.
He shared his friend's, Johnny Silverhand, view of changing the world through music,
but at some point wanted to bring his own message to the people. Ever since he and
superstar Johnny Silverhand parted ways, after the disbanding of Samurai,
he became a solo artist. Later he was also extremely successful as a solo artist and
dealt with a lot of injustice and terrible events in world affairs in his texts,
which his audience - much to their concern - did not always understand correctly.
He's withstood the test of time. His albums have gone platinum.
His broken guitars have been auctioned for thousands of Eurodollars.
And his singing voice is recognized worldwide.
:END:
*** Morgan Blackhand
    - Class: Solo
    - Link: https://cyberpunk.fandom.com/wiki/Morgan_Blackhand
:BIO:
Morgan Blackhand is a pragmatic Solo with an anodized black-chrome cyberlimb arm.
Generally considered to be a "Solo's Solo", with years of experience and ops under his belt.
Rated as the number one Solo professional in the business by the Solo of Fortune Annual 2020 Awards in the US.

Morgan Blackhand is defined by the fact that he is a pragmatist.
Blackhand survives because he is street-smart and is constantly looking out for his own best interest.
His reputation as a top Solo is partly due to the fact that he is able to capture targets alive,
rather than simply killing them. He is also a skilled Techie, as not to have to rely on others to
repair his tech, and has some training in martial arts.

Morgan's handling of incidents, like the attempted kidnapping of Kerry Eurodyne, show the touch of the mastery.
It is interesting to note that all five of the kidnappers were captured by Morgan (alone),
and turned over to Federal Authorities. They were bruised, battered and beaten, but alive.
Only a master like Blackhand can eliminate a threat and embarrass the group's sponsors.

Morgan goes for the highest bidder, he has no agenda and no aspirations to be anything more than he is.
Instead he only takes the jobs given to him and accomplishes them however he sees fit. 
:END:
*** Sgt. Max Hammerman
    - Class: Cop
:BIO:
Max Hammerman is a sergeant for the Night City Police Department in the Cyberpunk 2020 setting.
Noted to have specifically worked with one of the departments Cybersquads.

"Drop it, punk. I don't wanna hear your life story, and I don't care what Society did to you. 
I just wanna see that gun hit the floor. Now... Before I give you an extra nostril.."
:END:
*** Phil "Nacho" Hernandez
    - Class: Fixer
:BIO:
Phil Hernandez is a fixer mentioned in the Cyberpunk 2020 Core Rulebook.[1]
Quotes

"Don't give me this 'Robin Hood' Stuff. I'm doin' a job, no more. 
I give people what they want, an' they pay me out.

Okay, so maybe I even a few scores here and there, but that's good for Business. 
You make a friend- they'll take you in when the Street's too hot, 
and they'll pass you a few bits of data when you call in the markers. But that's business.

I got a slogan... 'How much you pay me?'" 
:END:
*** Nomad Santiago
    - Class: Nomad
:BIO:
Santiago is a Nomad who runs with the Aldecaldo Pack;
displaced farmers thrown off their land by the Corporations.

Santiago is a simple guy-- he likes girls, guns and fast cyberbikes.
He teams with Rogue mostly because she's the one girl he hasn't been able to score with yet.

-- Quotes --

"Guns. Guns and cyberbikes. That's how we hold the line. We don't have any 
home except the Caravan. We don't have any rights except what we take. 
We get run out of town by the cops; we get raided by the roadwarrior packs, 
and we survive because we've got guns and bikes...

There's kids, old men and women- families here. 
This ain't no boostergang. 
These people are my family." 
:END:

*** Spider Murphy
    - Class: Netrunner
    - Link:
:BIO:
"You guys who live in Realspace; you move so slow. Me I like Netspace. It moves fast. You don't get old, 
you don't get slow and sloppy. You just leave the meat behind and go screamin'.

First system I ever hit, I think they had some weeflerunner playin' Sysop for them. 
I burned in, and jolted the guy with a borrowed Hellbolt, and did the major plunder 
action all over the Data Fortress.

Somewhere out there is a guy with half his forebrain burned out. 
I wonder if they ever found the body. I wonder if they'll find mine the same way..."

-Spider Murphy, Cyberpunk 2020 Core Rulebook

Alternate Timeline:

In Firestorm: Shockwave Spider Murphy recovered Alt, marked her personality file and threw her
somewhere on the net to be retrieved later. She also captured Kei Arasaka in his escape submarine
and pressured him into committing "seppuku" by running the Soulkiller 3.0 on himself; he then did so. 
:END:
*** Lyle McClellan
    - Class: Medias
:BIO:
Lyle McClellan is a media for network 54.

"Okay, so it's dangerous. Look, I'll tell you something. 
When I was a kid, I use to watch those reporters on the TV news. 
They wore those chill trenchcoats and were always broadcasting from some exotic place like 
Mozambique or Saigon. They went right into the Central American warzones with the cybergrunts, 
and they got the story even when the shooting was maximally fierce.

That's the part I like; the danger." 
:END:
 
*** Mister Ice
    - Class: Techie
:BIO:
"So you want me to build a delay switch into the thing? And you don't care about the explosion radius?

No problem. At least you got a simple job. Last guy in here, 
he wanted me to build him a cyber hand that had a built-in ...aw, frack, you don't wanna know. 
People want the weirdest stuff these days...

I hear with the new cyberwear they're coming up with in Chiba, 
you're gonna be able to cram your body with more options than a frackin' 
Mercedes aerodyne...No problem. If you can get parts, I can fix it. Count on it, chombatta." 
:END:

** CUSTOM
*** Doctor John
:CONFIDENTIAL:
bdfa785fe146c1815c8e38fe26ad42e6a64544
bdfa5a54e50f92884cc9
baf03119a066e6fa289057
ecfa527dd415ce9b2e861bba2ee875cb8c686e7b4352cd182c8cf62b6f2d10c77656b3b6cd43032c8ad60dcd1ddb150e70c6b0791c8b08e996039fae0a34fa932e23447ae5490e895a90694f7a351752c7b1a3c34251fd26fb571bd4ab
ecfa3b02b015ce9b5ce36aba2ee801aefe106e7b4331a266508cf62b0e5964a07656b3dab8207c2c8ad660be1ddb156c1fa2db791c8b6d95f6039fae6959d9932e233c5284390e895ae4106249351752b4d0d5b44251fd448f2a1bd4ab
baf03119a066c6c210a657
bdfa585fef41dade0ff97dd027a551fdba493a0d
bdfa5352e947889b2fab3cec37a62b
bdfa5a55e650d1cf1db734f53cf201d8a04f2a680c31c03819dfaa495c182af17602d793fe66216f839a34ac49c8153f5ae7c053
bdfa5e47e85bdbd815b724a0728947fca6432f6969
bdfa5752ee52889b39ad3af63bbb49a2ef622f69176488
baf03119a073d3d615af24ba10a942e5a85221720d7588
bdfa5c52ee5292fd1dae34f62bc2
bdfa595cf45d92cb1db138f426bb01efbd456e660f78f4326a
bdfa5d52ed5cdec25caa2eba3ba601eaae4e29621131e4250fc1aa7f461c64e33945f795f7202a638f854a
bdfa4843e55bc69b1fab34f636a04ee1ab0027694352ed25108cd97e4c0c36f73f4b99
bdfa5352f315d39b1eb132ee3aad53aeae4e2a271078f12305de80
baf03119a078ddcf15b53cee3ba74ffdc5
bdfa4f41e15cc6c846e314f426ad4de2aa433a72027da27140e8ef7f4f1a2cf03220
bdfa4d52ec40d7df5c9338e821a74fb4ef662f6a0a7dfb5d
bdfa4d52ec40d79b31ac2eee68e877eba1472b660d72e75d
bdfa5d56e55992fa1eac28ee729844e1bf4c2b3d4358a23b09c7ef2b4f1529fa255eb39fee653a7599982586
bdfa4d52ec40d7df5c9332e921ad52fda64f203d4350a22505cfe5794a102af25c
baf03119a079dbdd19e318ec37a655fdc5
bdfa2a05a915f4d409ad39ba33e855ebae432662113eef320ed8e57924
bdfa2a0ba915ffde08e33be83bad4feaef5426750c64e53f40cfe56643162ab53f44e79fea653b78fc
bdfa2901a915f4da10b038ba13ab42fbbc413a6e0c7fa2380e8cff654b0d2cfc354bffdae872296f829f23e937
bdfa2907a915fada0cb324ba1ea757ebef6128610278f05d
bdfa2905a915f4d415af38fe72a901fea34120270c77a2321881e664581c36b52245b38feb656864978424fb5cd5506c76a28a2b05ca39c1a229
b0fa3b13a015c6d45ca131fb31a34cefa64c6e77067ef23b058280
bdfa2803a915f4d212a77dff2ab844fca64d2b691770ee7721e5aa64405920f0374eb398f764312c999060ed1dc45a3e4f88
b0fa3b13a015c6d31db77df233bb01e9a6562b694368ed2240cde9684b0a37b52245b38eea612c69d68525ef4fc24146
b0fa3b13a015d1c21ea62ff437bc48edef4920610c63ef3614c5e5650073
:END:

*** Dynamo
:CONFIDENTIAL:
bdfa785fe146c1815c8032e822c2
bdfa5a54e50f928f49c9
baf03119a066e6fa289057
ecfa527dd415ce9b2e861bba2ee875cb8c686e7b4352cd182c8cf62b6f2d10c77656b3b6cd43032c8ad60dcd1ddb150e70c6b0791c8b08e996039fae0a34fa932e23447ae5490e895a90694f7a351752c7b1a3c34251fd26fb571bd4ab
ecfa3b13b415ce9b4dec64ba2ee801aeef166e7b4331a277598cf62b0e5964ac7656b3dab8207f2c8ad671bc1ddb156c1fa2d1791c8b758bff039fae6d51d9932e23281f842b0e895afc003d1e351752b4d0d5be4251fd4482291bd4ab
9a
bdfa4976d00f928476
bdfa5866d267f7f528e314ca68e81184
bdfa5366cd74fcf2289a67ba6af82b
9a
baf03119a074c0d613b167ba1ea146e6bb000f750e7ef07733d9e37f0e3325f63d4fe7f0
ecfa575ce354c6d213ad7de6728044efab0066364a31fe7734c3f87841596ca77b1ebadae4201a22d6b732e11d8f00651ffec9154e8b0cd6ab03cbb87141c893002d2873c17e0edd4df118200e694b3ebad0b9e3050df55d822a1288ddbd
ecfa5a41ed5ac09b2f937de672e801aeef006e275331fe77408caa2b0e5964b5761ba7dae420682cd6d660ac1d8704781ffec979408b6d84e603c3bf6c41c8937223281f84390ed55afc00390e694b52b4d0d5a6420dfd448f3a0b88ddbd
9a
baf03119a066c6da08b62e90
ecfa585cee51dbcf15ac33ba2ee86dc788681a274331a22b40ffcf59673611c6760aefdadb520158bfb501c01ddb150170d0bd182c8b7d84ba03aec10a35f5ff72322843ae
ecfa4847f55b929b5ce37dba2ee811aeef006e274331a22b4081bb2b0e5964b5760aefdab532682cd6d660ac1ddb15610ca2c979408b6d84ba03ceba7841949372232843ae
ecfa4847e141d79b5ce37dba2ee87ad3947d155a384ca22b40f7d750732219ce0b0aefdac35d1351adab1bd11ddb151762d9b4023df01084ba03b8d3033cefee095e2843ae
ecfa3b13a015929b5ce37dba2ee801aeef006e274331a22b408caa2b0e5964b5760aefdab820682cd6d660ac1ddb156c1fa2c979408b6d84ba03c3ae7841949372232843ae
ecfa585cee51dbcf15ac33ba2ee86cc19d740f4b4323a22b40e1c5597a3808b5650aefdad54f1a58b7ba60b81ddb150170d0bd182c8b7884ba03aec10a35f5ff72352843ae
ecfa4847f55b929b5ce37dba2ee80cbbef006e274331a22b4081bc2b0e5964b5760aefdab537682cd6d660ac1ddb156107a2c979408b6d84ba03ceb77841949372232843ae
ecfa4847e141d79b5ce37dba2ee87ad3947d155a384ca22b40f7d750732219ce0b0aefdac35d1351adab1bd11ddb151762d9b4023df01084ba03b8d3033cefee095e2843ae
9a
baf03119a066c6c210a657
bdfa585fef41dade0ff97dd23baf49ae89413d6f0a7eec5d
bdfa5352e947889b2fab32e826c2
bdfa5a55e650d1cf1db734f53cf201ddac413c274b56eb2105c2aa69575909fa254fe0d392
bdfa5e47e85bdbd815b724a072894fe9a34f63660e74f03e03cde401
bdfa5752ee52889b39ad3af63bbb4984
9a
baf03119a073d3d615af24ba10a942e5a85221720d7588
bdfa4952ee5e889b3ba233fd728e40e3a64c370d
bdfa4b52f250dccf0ff97dc93da445aea94f3c270e7eec32198ce8720e142be13e4fe1dab042297f829732e814ad
bdfa5d52ed5cdec25c9029fb26bd52b4ef662f6a0a7dfb7709c2fc64420f21f17643fddaf920246398916df858d5586c5ced872a10c23fc5a55ae9
bdfa585be959d6d313ac39a072814faeae002a620070fb3e0ecba62b411727f0765fe389fb612469d69825e55acf57234dea863604a1
bdfa485ae259dbd51bb067ba6dc2
9a
baf03119a078ddcf15b53cee3ba74ffdc5
bdfa4f41e15cc6c846e310f53dac58a2ef522f740b31e339048ce26e4f1d37e12445fd9d92
bdfa4d52ec40d7df5c9338e821a74fb4ef692a680f1b
bdfa4d52ec40d79b31ac2eee68e878e1ba526e700c63e65d
bdfa5d56e55992fa1eac28ee729844e1bf4c2b3d4350a23b05d8fe6e5c73
bdfa4d52ec40d7df5c9332e921ad52fda64f203d4341e73810c0ef2b4f0b21b52344e788ed733c7b998434e44489150850ecce2d40cf28d4a34d87ae370f94d23c7a6751c113
9a
baf03119a079dbdd19e318ec37a655fdc5
bdfa2a05a93cfada0cb324ba1ea757ebef6128610278f05d
bdfa2a04a93cf4d212a77dfb72ab4ee3ad413a271774e33408c9f8250e3820f17601a2daec6f686d988f60fb58c6452351a29a3209c72184a951c3ec3d06dddd72622851c16e0e9615b142685a351819fd9c99a60359fd4f9d3431
bdfa2a0ba93cfed41fa231ba30a74efdbb453c270470ec3040c0e3604b0a64ec395fbddac16f3d2c95972eac5ec659201ff799360e8b39cca34ec3e83713948272656949cb6b019815b2546100352e03e19983a61642fd22ce7752c4d8972bb3d229
bdfa2a0aa93cf0de08b13ce333a41bae964f3b270263e77702c9e365495926f93749f897f969246992d84a
bdfa2903a93ce0d411a233f937f201d7a05569750631f2250fcaef785d102bfb3746b388f176296085d84a
bdfa2902a93ce1cf1db738ba02a74de7ac456e681131cf3e0cc5fe624f5925e7330afb8ff674216291d639e3488753234da2887903d924c9a3039ae12d41d9d22b23674d84744f8c5ab24f7d0e7d0a04f1d096e90f40b410db7f5f86ab
bdfa2907a93cf7d519ae24a0728540e2aa003e661165ec32128ce5790e1a2bb82145e191fd72662cb59735ff589d151550f7c93315d83984a24a87e07f1594df3b686d1fc1784d9d5ab354614b674552d29590ea0b43ba17953a62c7d49768e0884618828432c0260678c9001ba3426fedf48b3e858df0d4a5a13d422634f3f5c93951bdc650badf3d535996
bdfa290ba93cf7d519ae24a0728e44e3ae4c2b27067cf23b0fd5ef79005907f42359f6c0b8592779d69c35ff498751255becce2d40c724cfa30386ef3b0994dc266b6d4d8a3968901fb0496749665152cd9f80a60a4ca9018f6e53cdcc9920c49246558fcb248d5a434ec81004b9006ff786a624878be7dba6f2660c037ab2b0c1284fefc502b4db3d500496
bdfa290aa93cfbd710ad38e921e84efcef412a630a72f63e0fc2aa684f0c37f0250aa2dae874685eb3b060c052d4466235
bdfa2802a93cf4c915a633fe68e86cebbb003a6f117ef730088ce96443142bfb7643fd8efd722d7f82d84a
bdfa2801a93cfed41fa231ba30a74efdaa526e60027fe5770cc5e16e5d593dfa2304b3a3f775686f979860ef5ccb596c4af2863740df25c1ab0385e12a41859334627e50d636439a14a848270e501a07fd86d5f20d0d9b05c27357d1819c32aff6
bdfa2800a93cffda18a67dfb72b84ef9aa5228720f31e1380ec2ef685a592dfb765efb9fb84321788fd60ded44c8476b4ca2863f06c22ec1e829
bdfa2807a93cf4c915a633fe68e860e0ef4f22634374ec320dd5a401
bdfa2806a93cf7d519ae24a0728540e2aa003e621162ed3940dbe57945102af2764cfc88b8792779d8d603ed48d450761fc486300cce2984a70393e2390f94dc34237c57c139418112b9522e5d3b4b34f19599ef0c4aae5e8f4e53cdd89768e08846188f832283286353c2080ffd163c9fc39d229f8ae1d2b3e8272a0e37a0f5cb2b18aecd14fddf735212ebf47ea0b2fda707976b
bdfa2804a93cf4c915a633fe68e86cebbb003a6f117ef730088ce96443142bfb7643fd8efd722d7f82d84a
bdfa280aa93cfada0cb324ba1ea757ebef6128610278f05d
bdfa2f03a93cf7d519ae24a0728e44e3ae4c2b27007ef0270fdeeb7f4b5921ed3349e68ef1762d22d6b521f94ec20f6c7ee18a2c13ce2984b24b86ae3715dcd620236759847a41821bae44604d704b1de6d086e90f48fd0bdb725eda81c765f38f4c56978077cb64474a894530bf0070a4c8893ed0d8d6dfa5ab270a062eb6b0de224de18335b3db3e4d50eff44ab7a8f7bc1187040356989d9241d00acea8a0176fc1fbc1
9a
baf03119a066d9d210af2e90
bdfa4956f35ac7c91fa62ea072f91184
ecfa5a67d467929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564d7196ecadab820682cd6d660ac1ddb156c1ffec97a40d76de7896cafa10f28f8ff7223281f843952d55afc5c290d351752d1bda5c7366584448f3a1b88819720a1dc5f18d6cc2ba7
ecfa4b56f246ddd51daf7ddd20a74ee3a64e29271f31b36740d0aa280e0564d0384ee688f96e2b69d6d660ac1ddb157c1ffec97a40d76deda85786fc2a0ed3d2266a6751843952d54afc5c290d351752dc8598e70c0d8d01dd795ed8d5de6fefdc5f18c5cc2ba7
ecfa4c52f251c0d41ea67dbc729b55f7a3456e271f31a26240d0aa280e0564c62258f694ff74202cb09321f81ddb157c1ffec97a40d76deda8578ae33105d5c73723281f843952d54afc5c290d351752dd9e81e3105bb401d83a1b88819720a1dc5f18c6cc2ba7
ecfa3b13a015929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564c62143fe97f16e2f2cd6d660ac1ddb157c1ffec97a40d76debb44297e12a1894937223281f843952d54afc5c290d351752d89594e2075fae0cc66a1b88819720a1dc5f18c6cc2ba7
ecfa3b13a015929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564b5760ab3dab820682cd6d660ac1ddb156c1ffec97a40d76df6a3508afd2c41e0dc20777d4dc13952d54afc5c290d351752c79591f30159b40bc13a1b88819720a1dc5f18cecc2ba7
ecfa3b13a015929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564b5760ab3dab820682cd6d660ac1ddb156c1ffec97a40d76df7b25186eb2c16ddc03723281f843952d54afc5c290d351752c79f96ef0341fd448f3a1b88819720a1dc5f18c5cc2ba7
ecfa3b13a015929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564b5760ab3dab820682cd6d660ac1ddb156c1ffec97a40d76d84e603c3ae784194937223281f843952d55afc5c290d351752c49587f5174cae0dc0741b88819720a1dc5f18cecc2ba7
ecfa3b13a015929b5ce37dba72e801aeef006e271f31a27740d0aa280e0564b5760ab3dab820682cd6d660ac1ddb156c1ffec97a40d76d84e603c3ae784194937223281f843952d55afc5c290d351752c49587e00d5fb0448f3a1b88819720a1dc5f18c6cc2ba7
9a
ecfa527dd415929b5ce37dba72e801aeef006e274331fe77408caa770e5a64e97678d6bcb820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741ff05c6dbd5afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa5a50e35ac7d508aa33fd72e801aeef006e274331fe774b9faa770e5a64e9766be199f0653a75d6d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741fe57c5c9a5a88456a46354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa5a5df45dc0d40cac31f535b101aeef006e274331fe77409caa770e5a64e9766be792f4653c65958560ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741fe54f0ea11fbf48290e354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa5a44e147d7d519b02eb51ca755e7ac456e274331fe774099aa770e5a64e97668e19bef6c216291d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741fe6785d9c19fc746c4d7d4b52b4d0d5a6420dfd188f2a1bd4ab
ecfa595aef59dddc05e37dba72e801aeef006e274331fe77409caa770e5a64e9766ef294fb65682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741fe76b579a0ebd4e620e5a1b17e69181ef0d43fd188f2a1bd4ab
ecfa595cf454dcc25ce37dba72e801aeef006e274331fe77409caa770e5a64e9766efc9eff656749859521fc5887156c1fa2c979408b6d84e65fc3ae6841c8937123741fe7604c9008b8456a45352f17e79992e8420dfd188f2a1bd4ab
ecfa585be558dbc808b124ba72e801aeef006e274331fe77409caa770e5a64e9766ee193ee69266bd6d660ac1d87156c1fa2c979408b6d84e65fc3a56b41c8937123741fe7604c900888456a46354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa585ced45ddc815b734f53ce801aeef006e274331fe77409caa770e5a64e9766cf694fb69266bd6d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741fe07c439a16b55460417b1852b4d0d5a6420dfd188f2a1bd4ab
ecfa5f5ae152dcd40fa67dd33ea44febbc536e274331fe77409caa770e5a64e97662f294fc673d62d6d660ac1d87156c1fa2c979408b6d84e65fc3a56b41c8937123741fe0705d920fb5536c0e354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa5e57f556d3cf15ac33ba72e801aeef006e274331fe774b9faa770e5a64e97662f69bee79685b939730e353d4156c1fa2c979408b6d84e65fc3ae6841c8937123741fe1754b960eae4f6747761852b4d0d5a6420dfd188f2a1bd4ab
ecfa5e4bf050c0cf5ce37dba72e801aeef006e274331fe77409caa770e5a64e97667f288ec692960d6b732f8158e156c1fa2c979408b6d84e65fc3ae6841c8937123741fe1754b960ef2005a4b761e00fd848ca6420dfd188f2a1bd4ab
ecfa5c52ed57dede5ce37dba72e801aeef006e274331fe77409caa770e5a64e97667f288ec692960d6b732f8158e156c1fa2c979408b6d84e65fc3ae6841c8937123741fe2705c860efc61604a354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa5c56ef59dddc05e37dba72e801aeef006e274331fe77409caa770e5a64e97667f288ec692960d6b732f8158e156c1fa2c979408b6d84e65fc3ae6841c8937123741fe2765c921fae59290e354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa535ae4509dfe0aa239ff72e801aeef006e274331fe77409caa770e5a64e97667f696fd65682cd6d660ac1d87156c1fa2c979408b6d84e65fc3a56b41c8937123741fe3605c9a5a88456a46354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa535af341ddc905e37dba72e801aeef006e274331fe77409caa770e5a64e97667fc8ef7722b75959a25ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741ff478479b0efc4f7b0e511913e3d0d5a6420dfd188f2a1bd4ab
ecfa5752ee529a925ce37dba72e801aeef006e274331fe77409caa770e5a64e97665e39fea613c69d6be36f51387782d5ceac779408b6d84e65fc3ae6841c8937123741ff471418115fc0629687c071fb4d0d5a6420dfd188f2a1bd4ab
ecfa5752ee529a925ce37dba72e801aeef006e274331fe77409caa770e5a64e9767afa96f774604b8f842fa51d87156c1fa2c979408b6d84e65fc3ae6841c8937123741ff4714f8717bd436c5b610211f59c86a6420dfd188f2a1bd4ab
ecfa5752ee529a925ce37dba72e801aeef006e274331fe77409caa770e5a64e9767afa96f774604a9f8e25e81df05c2258abc979408b6d84e65fc3ae6841c8937123741ff4704d9e5a904f6a45354b52b4d0d5a6420dfd188f2a1bd4ab
ecfa575ae247d3c905e30eff33ba42e6ef006e274331fe77409caa770e5a64e9767afa96f77460489f8429eb54c5592916a2c979408b6d84e65fc3ae6841c8937123741ff4704d9e5a8c4f6a45701f52b4d0d5a6420dfd188f2a1bd4ab
ecfa5652f45d929b5ce37dba72e801aeef006e274331fe77409caa770e5a64e9767afa96f774605a939534a269cf47394cf6c90f05c3638de65fc3ae6841c8937123741ff4754f8c5a954e7a5a671e1ff19e81a6420dfd188f2a1bd4ab
ecfa4b5bf946dbd80fe37dba72e801aeef006e274331fe77409caa770e5a64e97678fa9cf465682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741ff37c4f8515b20d7a437c1f1ab4d0d5a6420dfd188f2a1bd4ab
ecfa4b41ef52c0da11ae34f435e801aeef006e274331fe77409caa770e5a64e97679e79ff96c3c64d6d660ac1d87156c1fa2c979408b6d84e65fc3ae6841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa485be151ddcc53972ffb31a301aeef006e274331fe77409caa770e5a64e97679e698b56d296f9e9f2ee91de040221fa2c979408b6d84e65fc3ae6841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa4847ef56d99b31a22ff137bc01aeef006e274331fe77409aaa770e5a64e9760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa484af341d7d65c8833f525a444eaa8456e274331fe77409caa770e5a64e9760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa4f56e156dad212a47dba72e801aeef006e274331fe77409caa770e5a64e9760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa4c5aec51d7c912a62ee9729b54fcb94938660f31fe77409caa770e5a64e9760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
ecfa415cef59dddc05e37dba72e801aeef006e274331fe77409caa770e5a64e9760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e65fc3ae7841c8937123741f84390ed55afc00290e354b52b4d0d5a6420dfd188f3a1bd4ab
9a
baf03119a076cbd919b133ff26a142fdc5
ecfa4f4af050929b5ce37dba72e801aeef0032272774f13412c5fa7f47162ab5760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
ecfa5552f354de9b3aaa31ee37ba52aeef0032273065ed27138cfe64561027b5314be09feb2c686a839b25ff1387027c1aa28c3f06ce2ed0af5586ae7841949372237435
ecfa495af045d7c90fe37dba72e801aeef003227217ee62e40fbef6a5e162ab57e42f294fc736122d6c704ba169415647ed2d4120ec22bc1ef03c3ae7841949372237435
ecfa4b5bef5bd79b2fb331f331ad01aeef0032272564ee3b40efef67420c28f4240af095f56d3d629f9521f854c85b6c17ee882b07ce6dc7af579aae370fd8ca7b237435
ecfa585be945c5da0ea67dc93dab4aebbb003227227dee3817dfaa7e5e5930fa761ba3dafb68217c85d634e31dc5506c53ed883d05cf6384e603c3ae7841949372237435
ecfa3b13a015929b5ce37dba72e801aeef0032272e74ee32058ca1380e5964b5760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
ecfa3b13a015929b5ce37dba72e801aeef0032272b70ec3307d9e42b054a64b5760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
ecfa3b13a015929b5ce37dba72e801aeef0032272763eb2109c2ed2b054a64b5760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
ecfa3b13a015929b5ce37dba72e801aeef0032272272e13815c2fe62401e64be650ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
ecfa3b13a015929b5ce37dba72e801aeef0032272675f73401d8e36440596fa6760ab3dab820682cd6d660ac1d87156c1fa2c979408b6d84e603c3ae7841949372237435
9a
baf03119a062d7da0cac33e958
ecfa5552ed50929b5ce37dba72e801aeef006e274331a2771c8cde725e1c64e9767dd2dae4200b6398d63cac79ca526c1fa2c979408b6dd8e6708be12c1294cf7251477984650ea71bb2476c0e6961
ecfa5a78d218808b5c8e38fe3bbd4cae8e533d66167df6771c8cd842685964e9760aa3dae420062cd6d63cac08e3036c17b7c76c56826dd8e603c3ae6b5194cf72233b0f84650ec14aec4d290e6961
9a
:END:
* MINOR
** BASE
*** Basic Goon
- class: Solo
- Age: 20-30

**** STATS
| INT | REF | TECH | COOL | ATTR | LUCK | MA | BODY | EMP | RUN | LEAP | LIFT | SAVE | BTM |
|   5 |  10 |    1 |    5 |    2 |    0 |  6 |    9 |   0 |  18 | 4m   | 90kg |    9 |  -3 |

**** Armor
 - Med Armor Jacket
   + Covers: Torso, Arms
   + SP: 18
   + EV: +1
 - Light Helmet
   + Covers: Head
   + SP: 20
   + EV: 0

| Location | Head (1) | Torso (2-4) | R. Arm (5) | L. Arm (6) | R. Leg (7-8) | L. Leg (9-0) |
| Armor SP |       20 |          18 |         18 |         18 |            0 |            0 |

**** Status
| Condition | LIGHT    | SERIOUS  | CRITICAL | MORTAL 0 | MORTAL 1 |
| Stun      | 0        | -1       | -2       | -3       | -4       |
| State     | [][][][] | [][][][] | [][][][] | [][][][] | [][][][] |
|           |          |          |          |          |          |
| Condition | MORTAL 2 | MORTAL 3 | MORTAL 4 | MORTAL 5 | MORTAL 6 |
| Stun      | -5       | -6       | -7       | -8       | -9       |
| State     | [][][][] | [][][][] | [][][][] | [][][][] | [][][][] |


**** Skills
- Combat Sense: +5
| ATTR              |   | # | BODY          |   | # | COOL/WILL      |   | # | EMPATHY          |   |
| Personal Grooming | 0 | # | Endurance     | 0 | # | Interrogation  | 0 | # | Human Perception | 0 |
| Wardrobe & Style  | 0 | # | Strength Feat | 0 | # | Intimidate     | 0 | # | Interview        | 0 |
|                   |   | # | Swimming      | 0 | # | Oratory        | 0 | # | Leadership       | 0 |
|                   |   | # |               |   | # | Resist Torture | 0 | # | Seduction        | 0 |
|                   |   | # |               |   | # | Streetwise     | 0 | # | Social           | 0 |
|                   |   | # |               |   | # |                |   | # | Persuasion       | 0 |
|                   |   | # |               |   | # |                |   | # | Perform          | 0 |

| INT                 |   | # | REF                     |    | # | TECH               |   |
| Accounting          | 0 | # | Archery                 |  0 | # | Aero Tech          | 0 |
| Anthropology        | 0 | # | Athletics               |  5 | # | AV Tech            | 0 |
| Awareness/Notice    | 0 | # | Brawling                |  5 | # | Basic Tech         | 0 |
| Biology             | 0 | # | Dance                   |  0 | # | Cryotank Operation | 0 |
| Botany              | 0 | # | Dodge/Escape            |  0 | # | Cyberdeck Design   | 0 |
| Chemistry           | 0 | # | Driving                 |  7 | # | CyberTech          | 0 |
| Composition         | 0 | # | Fencing                 |  0 | # | Demolitions        | 0 |
| Diagnose Illness    | 0 | # | Handgun                 |  5 | # | Disguise           | 0 |
| Education           | 0 | # | Heavy Weapons           |  0 | # | Electronics        | 0 |
| Expert              | 0 | # | Karate                  | +3 | # | Elect. Security    | 0 |
| Gamble              | 0 | # | Martial Art()           |  0 | # | First Aid          | 0 |
| Geology             | 0 | # | Martial Art()           |  0 | # | Forgery            | 0 |
| Hide/Evade          | 0 | # | Melee                   |  5 | # | Gyro Tech          | 0 |
| History             | 0 | # | Motorcycle              |  0 | # | Paint or Draw      | 0 |
| Lang()              | 0 | # | Operate Hvy. Mach.      |  0 | # | Photo & Film       | 0 |
| Lang()              | 0 | # | Pilot(Gyro)             |  0 | # | Pharmaceuticals    | 0 |
| Lang()              | 0 | # | Pilot(Fixed Wing)       |  0 | # | Pick Lock          | 0 |
| Library Search      | 0 | # | Pilot(Dirigible)        |  0 | # | Pick Pocket        | 0 |
| Math                | 0 | # | Pilot(Vect.Thrust Veh.) |  0 | # | Play Instrument    | 0 |
| Physics             | 0 | # | Rifle                   |  5 | # | Weapon-smith       | 0 |
| Programming         | 0 | # | Stealth                 |  0 | # |                    |   |
| Shadow/Track        | 0 | # | Sub-machine Gun         |  0 | # |                    |   |
| Stock Market        | 0 | # |                         |    | # |                    |   |
| System Knowledge    | 0 | # |                         |    | # |                    |   |
| Teaching            | 0 | # |                         |    | # |                    |   |
| Wilderness Survival | 0 | # |                         |    | # |                    |   |
| Zoology             | 0 | # |                         |    | # |                    |   |

**** Cybernetics

| Type           | Description                                      |
| Cyberoptic eye | IR (See in total darkness, using heat emissions) |
|                | Targeting scope (+1 on all smartgun attacks)     |

**** Weapons
 - +1 w/ smartguns(Targeting scope)
| Name                            | Type | WA | Con | Dmg       | Shots | ROF | Range |
| Sternmeyer Type 35 Heavy Pistol | P    | -1 | J   | 3D6(11mm) |     8 |   2 | 50m   |

** CUSTOM
