[[file:index.org][Return to Home]]
* STATISTICS
** Intelligence (INT)
    - This is a measure of your problem solving
      ability; figuring out problems, noticing
      things, remembering information. Almost
      every character type will need a high Intel-
      ligence, with Netrunners and Corporates
      requiring the highest of all.
      
** Reflexes (REF)
   - This is a combined index, covering not
     only your basic dexterity, but also how
     your level of physical coordination will
     affect feats of driving, piloting, fighting
     and athletics. Characters who intend to
     engage in a great deal of combat (such as
     Solos, Nomads or Rockerboys) should
     always invest in the highest possible Reflex

** Cool (CL)
   - This index measures how well the charac-
     ter stands up to stress, fear, pressure, physi-
     cal pain and/or torture. In determining
     your willingness to fight on despite wounds
     or your fighting ability underfire, Cool(CL)
     is essential. It is also the measure of how
     “together” your character is and how
     tough he appears to others. Rockerboys
     and Fixers should always have a high Cool,
     with Solos and Nomads having the highest
     of all.
     
** Technical Ability (TECH)
   - This is an index of how well you relate to
     hardware and other technically oriented
     things. In Cyberpunk, the ability to use and
     repair technology is of paramount impor-
     tance - TECH will be the Stat used when
     fixing, repairing and attempting to use
     unfamiliar tech. While all characters should
     have a decent Tech Stat, potential Techies
     should always opt for the highest possible
     score in this area.

** Luck (LK)
   - This is the intangible “something” that
     throws the balance of events into your
     favor.Your luck represents how many points
     you may use each game to influence the
     outcome of a critical event. To use Luck,
     you may add any or all of the points of luck
     a character has to a critical die roll (declar-
     ing your intentions to use Luck before the
     roll is made) until all of your Luck stat is
     used up. Luck is always restored a the end
     of each game session.

** Attractiveness (ATT)
   - This is how good-looking you are. In
     Cyberpunk, it's not enough to be good-you
     have to look good while you're doing it
     (Attitude is Everything). Attractiveness
     is especially important to Medias and
     Rockerboys, as being good-looking is part
     of their jobs.

** Movement Allowance (MA)
   - This is an index of how fast your character
     can run (important in combat situations).
     The higher your Movement Allowance
     (MA), the more distance you can cover in
     a turn.
   - RUN: To determine how far your character
          can run in a single combat round
          (@3.2 seconds) in meters, multiply your
          MA by 3. The character can run three
          times this distance in a full 10 second
          turn. Write this in the RUN section of your
          Hardcopy Form.
   - LEAP: To determine how far your character 
           can leap (from a running start), divide
           your RUN by 4. Write this in the LEAP
           section of your Hardcopy Form.

** Empathy
   - This Stat represents how well you relate to
     other living things-a measure of charisma
     and sympathetic emotions. In a world of
     alienated, future-shocked survivors, the
     ability to be “human” can no longer be
     taken for granted. Empathy (EM) is critical
     when leading, convincing, seducing or
     perceiving emotional undercurrents. Em-
     pathy is also a measure of how close he/she
     is to the line between feeling human being
     and cold blooded cyber-monster (see pg.
     73 for details).
   - Humanity : This is a
                measure of the toll
                cybernetics takes on
                your ability to relate to
                other living things.
                Multiply your EMP by
                10 to determine how
                many humanity points
                you have. Write the
                result in the box on your
                Hardcopy Form. Remember: for every 10
                points of Humanity lost, you will auto-
                matically lose 1 point of EMP. This can
                have a serious effect on any Empathy-
                related Skills, as well as forcing you to the
                edge of cybernetic-induced psychosis.

** Body Type (BT)
   - Strength, Endurance and Constitution are
     all based on the character's Body Type.
     Body Type determines how much damage
     you can take in wounds, how much you
     can lift or carry, how far you can throw (pg.
     99), how well you recover from shock, and
     how much additional damage you cause
     with physical attacks. Body Type is impor-
     tant to all character types, but to Solos,
     Rockerboys and Nomads most of all.
   - BODY TYPES & POINTS
     | 2 pts   | Very Weak   |
     | 3-4 pts | Weak        |
     | 5-7 pts | Average     |
     | 8-9 pts | Strong      |
     | 10 pts  | Very Strong |
   - You may carry up to 10x your Body Type
     in kg. You may also dead lift 40 times your
     Body Type in kg.

*** Save Number
    - Your character's Save Number is a value
      equal to your Body Type. To make saves,
      you must roll a value on 1D10 equal to or
      lower than this number. There are two
      types of saves in Cyberpunk:
     
      - Stun Saves: When you take damage in
        Cyberpunk, or have been exposed to
        knockout drugs, you will be required to
        make a Stun Save. If you fail a Stun Save,
        you will automatically be knocked out of
        combat and be unable to recover until you
        can make a successful Stun Save in a
        following combat turn.You may make one
        Save roll every turn until you succeed.

      - Death Save: When you have been Mortally
        Wounded (see Friday Night Firefight, pg.104),
        or when you have encountered certain types of
        poisons, you will need to make a Save against
        Death. On a failed roll, you're Body Bank fodder.

** Body Type Modifier (BTM)
   - Not all people take damage the same way.
     For example, it takes a lot more damage to
     stop Arnold The Terminator than it does
     Arnold the Nerd. This is reflected by the
     Body Type Modifier, a special bonus used
     by your character to reduce the effects of
     damage. The Body type modifier is subtracted 
     from any damage your character takes in combat.

   - Body Type Modifier Table
     | Very Weak                 | -0 |
     | Weak                      | -1 |
     | Average                   | -2 |
     | Strong                    | -3 |
     | Very Strong               | -4 |
     | Superhuman* (Cybernetics) | -5 |

     - For example, say you took ten points of
       damage. If you were a Very Weak Body Type,
       you would take the full ten. But with a Very
       Strong Body Type, you'd only take (10-4=6)
       six points of damage.


* Reputation
  - Reputation is a measure of things your character
    may do so well (or badly) that he has actually become
    well known for them. A reputation for something is always
    established by a character's actions, and is then awarded
    by the Referee. Whenever a character encounters new people in new
    situations , his reputation may actually influence how they
    react to him. Sometimes this can be very good.
    Other times, it can be very bad.
** Facedowns
   - When making a facedown, both participants will roll:
     *1D1O + COOL + REPUTATION*

     Note: If one of the opponents has a repu-
           tation for cowardice, his value will be
           treated as a negative number.
           In a facedown, the loser has the option of
           backing down or making any subsequent
           attacks against this particular opponent
           at a -3 (due to fear) until he has success-
           fully defeated that opponent once. On a
           tied roll, both parties are unsure and no
           penalties will apply.

** Reputation Table
| Level | Who Knows About You                                          |
|-------|--------------------------------------------------------------|
|     1 | Anyone who was there at the time knows.                      |
|     2 | Stories have gotten around to immediate friends.             |
|     3 | All your co-workers and casual acquaintances know.           |
|     4 | Stories are all over the local area.                         |
|     5 | Your name is recognized by others beyond your local area.    |
|     6 | You are known on sight by others beyond your local area.     |
|     7 | A news story or two has been written about your exploits.    |
|     8 | Your exploits regularly make the headlines and screamsheets. |
|     9 | Your exploits always make the screamsheets and TV.           |
|    10 | You're known worldwide.                                      |

